### ISSUE TITLE
Fixing the text in the RSS feed hover menu

### ISSUE THREAD

**Issue by not-a-dev-stein** [makedeb/mprweb#1]
Just a small fix needed to the website, to change the text in the RSS feed box from "Arch Package Updates RSS Feed" to MPR or makedeb.

![Captura de tela de 2021-07-21 01-58-18](https://user-images.githubusercontent.com/63420929/126433337-26fa75ed-dc2a-42be-9ea7-9aceb6ae94f4.png)

**Comment by hwittenborn** [comment]
I just pushed a commit that should (hopefully) fix the issue. I'll do some testing within a few days when I get some time, and I'll just leave this issue open until then in case it actually didn't fix anything.

**Comment by hwittenborn** [comment]
Should be fixed to the deployed instance now :)
