### ISSUE TITLE
RSS does not show author or icon

### ISSUE THREAD

**Issue by zocker-160** [makedeb/mprweb#10]
## currently
![image](https://user-images.githubusercontent.com/36563538/146935551-9f3feba2-67b5-46c0-a596-1a2f53522010.png)

before the mprweb Python update at least the authors did work
![image](https://user-images.githubusercontent.com/36563538/146935688-962f8641-ca4f-4d20-87f9-0edc8cac259c.png)

**Comment by cat-master21** [comment]
On Quiterss I can see icons fine however the Author section is still missing though:
![MPR-newest-packages](https://user-images.githubusercontent.com/96554164/148709539-eb700dfe-8f75-4530-b41a-e01b13792896.png)

**Comment by hwittenborn** [comment]
Can you see if you get the same results with the AUR's RSS @zocker-160?

**Comment by zocker-160** [comment]
@hwittenborn on the AUR RSS the icons work, the author does not though.
