### ISSUE TITLE
Unable to reset password

### ISSUE THREAD

**Issue by cristobaltapia** [makedeb/mprweb#113]
### Issue

Hi,

I was trying to reset my password. I got the Email with the link to do this, but the link throws an Error 404.

**Comment by hwittenborn** [comment]
Hey, thanks for reporting the issue! I'm not sure if you've tried it yet, but could you trying sending a new password reset email and see if that works?

**Comment by cristobaltapia** [comment]
Hi @hwittenborn, I just tried again, but the error is still there. I get:

```
404 Not Found
nginx/1.22.0 (Ubuntu)
```

**Comment by hwittenborn** [comment]
Hmm, alright, something's got to be up then, I was suspecting it was just an outdated email or something, but it doesn't look like that's the case.

I'm gonna check some logs, and I'll get back to you once I have some more info.

**Comment by hwittenborn** [comment]
@cristobaltapia: It looks like there was an issue with a config file on the MPR server that caused some weird stuff with redirects (which the emails that get sent out appear to currently be doing). I just changed some stuff that should've fixed the issue though - can you check on your end if it's the same?

**Comment by cristobaltapia** [comment]
Now it worked! Thanks for the quick bug-fix!
