### ISSUE TITLE
you probably, shouldn't be forking this

### ISSUE THREAD

**Issue by ghost** [makedeb/mprweb#116]
### Description of feature.

maybe, instead of forking this, you should be with upstream to make that more generic?

**Comment by hwittenborn** [comment]
The MPR has some features that simply aren't required by the upstream AUR project (such as distro/architecture listings), and having those merged upstream just doesn't make a bunch of sense imo.

I wouldn't object to such an initiative if it were to happen, but I can't see myself leading anything of the sort anytime soon. The makedeb project as a whole isn't something I've had a ton of time for recently (I've been quite busy with school and other projects like Celeste), so I can't see myself driving forward something major like this right now.

**Comment by ghost** [comment]
in general, software is made to accommodate many users. Yes, this mean that a given user uses few features. Yes, this mean they will be stuff, that Arch doesn't use and the mpr does and vice versa. Did you wright your own kernel and use all it's features?

I think this is saner then forking it out right. Of course, it also depends on upstream.
