### ISSUE TITLE
Receive server error when attempting to view changes of `PKGBUILD`

### ISSUE THREAD

**Issue by taivlam** [makedeb/mprweb#119]
### Issue

Not sure what is happening, but every time I try to view changes to a `PKGBUILD` on the MPR website, I receive an error that says:

> Server Error
> There was an issue processing your request.
> 
> This incident has not been logged, as your browser has the Do-Not-Track header enabled. If you keep experiencing this issue, please [report an issue](https://github.com/makedeb/mprweb/issues) or reach out in [makedeb's support rooms](https://docs.makedeb.org/support/obtaining-support/).

For example, this is happening when I try to [view changes made](https://mpr.makedeb.org/pkgbase/bitwarden-bin/git/commit/latest) to `bitwarden-bin`. 

This has been happening for at least 1-2 weeks (if not longer).

This also happens when I try to [view the Git tree](https://mpr.makedeb.org/pkgbase/bitwarden-bin/git#git-tree) of `bitwarden-bin`.

**Comment by hwittenborn** [comment]
This should now be fixed on the MPR.

**Comment by taivlam** [comment]
Thank you!
