### ISSUE TITLE
Some packages cannot be marked out of date

### ISSUE THREAD

**Issue by hiddeninthesand** [makedeb/mprweb#13]
I'm aware that some of the devs are already aware of this issue, but I didn't see it marked down so I'm taking the opportunity to. There's a bug among some MPR packages that make them incapable of being marked out of date, one of which being [Android Studio.](https://mpr.hunterwittenborn.com/packages/android-studio) If extra information is required, I'll try my best to provide it.

**Comment by hwittenborn** [comment]
I'm assuming this was a bug in a previous version of the MPR, but I won't really know unless it happens to any other packages.

Your issue with Android Studio should be fixed though.

**Comment by hiddeninthesand** [comment]
Thanks, it's resolved!
