### ISSUE TITLE
[Feature Request] Status/Uptime page for mprweb

### ISSUE THREAD

**Issue by hiddeninthesand** [makedeb/mprweb#17]
Sometimes mprweb and the MPR as a whole goes down with no sanity checks besides checking the Matrix rooms, and a status page could go a long way in alleviating that.

**Comment by lpuv** [comment]
For now, https://mpr-stat.craftcat.dev/status works!

**Comment by hiddeninthesand** [comment]
At least at the time of this message, that site gives me a 502 :(

**Comment by hwittenborn** [comment]
Just looking more into this, and it looks like we'll probably do something similar to such for everything:

It looks like we're gonna be using Atlassian Statuspage to monitor all the infrastructure (a page already exists at https://homelab.statuspage.io/, we just need to set it up with all the other services and get it hosted on https://status.hunterwittenborn.com). I'd like to be able to easily allow TUs and other figures to post status updates automatically though, so we'll probably set up one (if not both) of the following:

- Email bot; This will accept emails from certain users and post status updates via such (it looks like Statuspage might have native integration for this, though I'm not sure if I can restrict the email addresses it will accept). This would primarily be as a fallback when my Matrix server itself is down, and requests can't be processed through there.
- Matrix bot; This is main method that I'd like to use. Statuspage has an API that we can use, so we'll probably just allow messages from certain users to go through, and then the bot will process them. Current plan would be to use the [simple-matrix-bot-lib](https://github.com/KrazyKirby99999/simple-matrix-bot-lib) library, as it looks really nice for easily handing a request when a message is received (looks similar to how discord.py runs, and I'd like to use this as an excuse to try it out too :p).

**Comment by hwittenborn** [comment]
Status page is at https://status.makedeb.org
