### ISSUE TITLE
[Feature Request] Show how many times a package has been cloned

### ISSUE THREAD

**Issue by hiddeninthesand** [makedeb/mprweb#33]
mprweb could tally the cloning of any given package, giving users and package maintainers a much more realistic at-a-glance number to determine package popularity than the current option.

**Comment by hwittenborn** [comment]
From what I'm first seeing right now, the only information I can really get is every time the client *pulls*.

This is true at least for the SSH interface - running `ssh` with verbose logging during the clone is showing that the only command that is sent is `git-upload-pack '{pkgbase}'`, with no other information being sent, regardless of running `git clone` or `git pull`. I honestly have 0 clue how GitHub is reporting accurate statistics for stuff like this.

Would pulls be an acceptable alternative?

**Comment by hiddeninthesand** [comment]
Sounds like a good alternative to me.
