### ISSUE TITLE
[Feature Request] Delete self-deleted comments

### ISSUE THREAD

**Issue by hiddeninthesand** [makedeb/mprweb#34]
Currently, self-deleted comments are treated like TU deleted comments, in which they aren't actually deleted from the mprweb server, but merely hidden to everyone but the TU and the original poster (with the ability to be unhidden). This is somewhat problematic from a privacy perspective, so an option to truly delete self-deleted comments would be appreciated.

**Comment by hwittenborn** [comment]
We want to keep all comments so we know that a user didn't delete something to just hide it or something. If you don't want something said by you on the MPR just don't say it :p

I'm all for privacy, but adding an option for normal users to delete comments (and possibly even TUs) could be problematic in the event of a dramatic situation going on.
