### ISSUE TITLE
icons for the comment actions do not show up properly

### ISSUE THREAD

**Issue by zocker-160** [makedeb/mprweb#4]
![Screenshot_20211118_170525](https://user-images.githubusercontent.com/36563538/142515992-32a20e6f-0c09-4b52-b463-b111f5769a78.png)

**Comment by hwittenborn** [comment]
This appears to have been fixed after merging in some upstream changes a bit ago. Could you confirm if it's also such on your end?

**Comment by zocker-160** [comment]
it does work indeed, I guess it was fixed upstream then
will close
