### ISSUE TITLE
Add button to install packages via MPR helpers

### ISSUE THREAD

**Issue by hwittenborn** [makedeb/mprweb#48]
It would be nice to have a button that could bring up a window that showed instructions for installing packages with various MPR helpers.

**Comment by hiddeninthesand** [comment]
Wouldn't something like xdg-open be good for this?

**Comment by hwittenborn** [comment]
I don't see any reason we couldn't do that - my current plan was to just allow helpers to add their own text for how to install, so they'd be able to provide `xdg-open` commands themselves.

**Comment by hwittenborn** [comment]
Closed in https://github.com/makedeb/mprweb/commit/c43a7f076bc8d4ae236e683b3084ae45310fc79f.
