### ISSUE TITLE
Unable to log in to mprweb

### ISSUE THREAD

**Issue by hiddeninthesand** [makedeb/mprweb#7]
Steps to reproduce:
1. Open https://mpr.hunterwittenborn.com/login?next=/
2. Enter Credentials
3. Encounter a 500 internal server error

The only error mentioned is that it's "Unable to generate a unique session ID in 36 iterations."

**Comment by hwittenborn** [comment]
Are you still getting the error? Attempting to login with both my account and a bot account is working just fine on my end.

**Comment by hiddeninthesand** [comment]
> Are you still getting the error? Attempting to login with both my account and a bot account is working just fine on my end.

Indeed, this happens on every browser I have.

**Comment by hwittenborn** [comment]
Solved in the Matrix support rooms - feel free to reopen if you're still having the issue.
