### ISSUE TITLE
Internal Server Error upon attempting to hide email address

### ISSUE THREAD

**Issue by hiddeninthesand** [makedeb/mprweb#8]
Steps to reproduce:
1. Log in to mprweb
2. Go to account settings
3. Check "Hide Email Address" and enter password where required
4. Click button to save, and be met with ISE

Not sure what's going on here, but I'll be happy to provide information where I can.

**Comment by hwittenborn** [comment]
I just merged in some upstream changes - could you confirm if the issue still happens for you so I know if I need to keep investigating?

**Comment by hiddeninthesand** [comment]
Same results, no change.

**Comment by hwittenborn** [comment]
Just merged in some upstream changes again - could you see if the errors persists this time?

~~I think you should get the error directly this time as well :)~~

**Comment by hiddeninthesand** [comment]
It changed! It now shows a proper fancy 500 ISE instead of an empty page. Still doesn't work, but progress has been made.

**Comment by hwittenborn** [comment]
Ignore that commit reference, that's for in issue in the upstream project :P

**Comment by hwittenborn** [comment]
Sorry for the delay, but I just did some testing and I'm able to reproduce the issue on my end. Looking into it now.

**Comment by hwittenborn** [comment]
Just found the root cause - I'm just running unit tests real quick then I'll push the fix.
