### ISSUE TITLE
Can't disown a package (unable to check the confirmation box)

### ISSUE THREAD

**Issue by R8s6** [makedeb/mprweb#84]
It is required to check the "Confirm to disown the package " box before disowning, but clicking the box has no effect, and therefore, I can't disown a package.

I tried on Firefox and Chromium, and had the same problem.

Could you please kindly take a look?

Thank you very much.

**Comment by hwittenborn** [comment]
I think I've experienced the same issue myself, it's just gone over my head every time the issue's came up.

Thanks for making the issue, I'll get it fixed shortly.

**Comment by hwittenborn** [comment]
Until I can get a fix in, you can disable the `pointer-events: none` CSS code in your browser's dev tools. If you can't do that, just let me know what packages you want orphaned and I can get that going.

You can also disown it via the [API](https://mpr.makedeb.org) if you want to try that.

**Comment by hwittenborn** [comment]
This should be fixed now. Feel free to comment or make a new issue if you're still experiencing problems.

**Comment by R8s6** [comment]
Thank you very much.
