### ISSUE TITLE
account creation not possible

### ISSUE THREAD

**Issue by gebi** [makedeb/mprweb#85]
Hi,

wanted to get my aur packages on debian too, but seem account creation is not possible with the makedeb version installed from stable apt repo.

Error: `The entered CAPTCHA answer is invalid.`

![image](https://user-images.githubusercontent.com/659/167864100-a502b69d-ee6f-42b5-b8da-5cb1779c9f7a.png)

## Cmd used

```
# makedeb --mpr-check | sed -r 's#[0-9]+#509#g' | md5sum | cut -c1-6
e37bd2
```

Usefull for debugging
```
# makedeb --mpr-check

 .--.                  Pacman v6.0.0 - libalpm v13.0.0
/ _.-' .-.  .-.  .-.   Copyright (C) 2006-2021 Pacman Development Team
\  '-. '-'  '-'  '-'   Copyright (C) 2002-2006 Judd Vinet
 '--'
                       This program may be freely redistributed under
                       the terms of the GNU General Public License.
#
```

## Env

```
# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux bookworm/sid
Release:        unstable
Codename:       sid
```

```
# uname -a
Linux XXX 5.16.0-6-amd64 #1 SMP PREEMPT Debian 5.16.18-1 (2022-03-29) x86_64 GNU/Linux
```

```
# apt-cache policy
 500 https://proget.hunterwittenborn.com makedeb/main all Packages
     release a=stable,n=makedeb,c=main,b=all
     origin proget.hunterwittenborn.com
```

**Comment by hwittenborn** [comment]
I'm at school rn and I'm gonna be busy for the next couple of days, so I probably won't be able to look at this for a bit.

Do you have access to an Arch machine right now? If so, getting the output of `pacman -V` and comparing it to makedeb's output (see if there's any extra newlines or anything) might reveal something.

**Comment by hwittenborn** [comment]
Looking into this now @gebi, and it looks like makedeb's `--mpr-check` command is missing some output.

If you replace the following in the CAPTCHA command, it should work for signups for the time being:

```sh
makedeb --mpr-check |
```

```sh
(makedeb --mpr-check; printf '\n') |
```

**Comment by gebi** [comment]
awesome thx, the hint with using arch for the captcha worked

screenshot of vimdiff of output of `makedeb --mpr-check` compared between debian/arch
![image](https://user-images.githubusercontent.com/659/168316404-aee10eba-3803-4318-91e1-326525bf3dff.png)

As you spotted, yes there is a newline missing at the end and the version is different.

this cmd now produces the same captcha on debian as the one without `\n` on arch
```
% (makedeb --mpr-check; printf '\n') | sed -r 's#[0-9]+#509#g' | md5sum | cut -c1-6
```

**Comment by hwittenborn** [comment]
I'm gonna leave this open until the issue is fixed in makedeb, just so other people know the issue exists if they come to this repository.

**Comment by hwittenborn** [comment]
Fixed in the latest release of makedeb.
